name: Build and release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Build exec
      run: |
        pyinstaller --onefile pdf.py

    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: ./dist/pdf.exe

  release:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: dist
    - name: Archive content
      uses: thedoctor0/zip-release@master
      with:
        filename: app.zip

    - name: Set variables
      run: |
        echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.VERSION }}
        release_name: Release ${{ env.VERSION }}
        body: |
          Release ${{ env.VERSION }}
        draft: false
        prerelease: false
        commitish: ${{ github.sha }}
      env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Publish release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./app.zip
        asset_name: pdfManager_${{env.VERSION}}.zip
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}